// 一命 · SEO 扩展词条（仅用于静态页生成，不进 app 内词典）
// 全部取公有命理框架，自己的话重写；标公有古籍出处；只解释/谈性格倾向，不预测、不改运。

// ——— 十神细分（10）———
export const SHISHEN = [
  {
    id: 'zhengguan', kind: 'shishen', zh: '正官', en: 'Direct Officer',
    defZh: '正官代表约束、责任、规矩与地位，是"克我而有情"的力量，象征自律、社会规范与正当的权威；女命也常看作夫星。',
    defEn: 'Direct Officer stands for discipline, responsibility, rules and status — a restraining yet benevolent force symbolizing self-control and legitimate authority.',
    relZh: '正官最忌伤官来克（"伤官见官"），喜印来通关化护、喜财来生官。',
    relEn: 'It is most undermined by Hurting Officer; it likes Resource to mediate and Wealth to feed it.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'qisha', kind: 'shishen', zh: '七杀（偏官）', en: 'Seven Killings',
    defZh: '七杀是"克我无情"的力量，代表压力、挑战、魄力与竞争，也是磨砺与权威。制化得当则为将才魄力，失制则易冲动受压。',
    defEn: 'Seven Killings is an unrestrained controlling force — pressure, challenge, drive and competition. Well-tamed it becomes grit and leadership; untamed, stress and impulsiveness.',
    relZh: '七杀喜食神来制（"食神制杀"）、印来化（"杀印相生"），最怕身弱杀旺。',
    relEn: 'It welcomes Eating God to curb it and Resource to transform it; the danger is a weak self facing strong Killings.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'zhengyin', kind: 'shishen', zh: '正印', en: 'Direct Resource',
    defZh: '正印代表学识、母亲、靠山、滋养与名誉，是"生我而有情"的力量，象征被保护、被滋养、重名声与文化。',
    defEn: 'Direct Resource means learning, the mother, backing, nurture and reputation — a generating, protective force.',
    relZh: '正印能化官杀之克（化压力为助力）、能制食伤；印过多则易依赖、欠行动。',
    relEn: 'It turns the pressure of Authority into support and curbs Output; too much can breed dependence.',
    src: '十神，《三命通会》',
  },
  {
    id: 'pianyin', kind: 'shishen', zh: '偏印（枭神）', en: 'Indirect Resource',
    defZh: '偏印又称枭神，代表偏门学问、直觉、独特思维与技艺，也含孤、淡情、不走寻常路之意，常见于有专长、想法奇特的人。',
    defEn: 'Indirect Resource (the "Owl") means unconventional learning, intuition and niche skill — often with a streak of detachment and originality.',
    relZh: '偏印夺食（克食神）为忌，喜财来制偏印；得用则多偏才异能。',
    relEn: 'It clashes with Eating God; Wealth can rein it in, and when useful it brings unusual talent.',
    src: '十神，《三命通会》',
  },
  {
    id: 'zhengcai', kind: 'shishen', zh: '正财', en: 'Direct Wealth',
    defZh: '正财代表稳定的财、勤俭务实与正当所得，象征靠努力积累的资源；男命也常看作妻星。',
    defEn: 'Direct Wealth is stable, earned income — thrift, diligence and legitimate gain.',
    relZh: '正财喜身强能担、喜食伤来生；最忌比劫来夺（"比劫夺财"）。',
    relEn: 'It wants a strong self to "carry" it and Output to feed it; it fears Companions stealing it.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'piancai', kind: 'shishen', zh: '偏财', en: 'Indirect Wealth',
    defZh: '偏财代表流动的财、机会财与意外之得，为人多慷慨、善交际、重人缘，财来财去较快。',
    defEn: 'Indirect Wealth is flowing, opportunistic money — generous, sociable, good with people, money coming and going quickly.',
    relZh: '偏财同喜身强、食伤生；身弱财旺则"财多身弱"，反为所累。',
    relEn: 'Like Direct Wealth it wants a strong self; a weak self with heavy Wealth is burdened by it.',
    src: '十神，《三命通会》',
  },
  {
    id: 'shishen', kind: 'shishen', zh: '食神', en: 'Eating God',
    defZh: '食神代表才华、表达、口福与福气，是温和从容的"输出"，象征享受、创造与亲和力。',
    defEn: 'Eating God means talent, expression, good fortune and ease — a gentle, creative output.',
    relZh: '食神能生财、能制七杀（"食神制杀"）；最怕偏印来夺（"枭印夺食"）。',
    relEn: 'It feeds Wealth and curbs Seven Killings; its enemy is Indirect Resource.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'shangguan', kind: 'shishen', zh: '伤官', en: 'Hurting Officer',
    defZh: '伤官代表才气外露、创造力与叛逆，聪明锋利、不服管束、表现欲强，是激烈版的"输出"——用得好是才华，用不好是是非。',
    defEn: 'Hurting Officer is talent on display — clever, sharp, rebellious and expressive; brilliance when channeled, friction when not.',
    relZh: '伤官最克正官（"伤官见官，为祸百端"），喜财来流通（"伤官生财"）、印来制。',
    relEn: 'It strongly clashes with Direct Officer; it likes Wealth to channel it and Resource to restrain it.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'bijian', kind: 'shishen', zh: '比肩', en: 'Friend (Parallel)',
    defZh: '比肩与日主同类同性，代表自我、独立、同辈与合作，象征主见与并肩的力量，也含分担与分享。',
    defEn: 'Friend (Parallel) shares the Day Master’s element and polarity — self, independence, peers and cooperation.',
    relZh: '比肩助身（身弱喜之），亦会分财（身旺则嫌其夺）；是判旺衰的关键之一。',
    relEn: 'It supports a weak self but competes for Wealth when the self is strong.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'jiecai', kind: 'shishen', zh: '劫财', en: 'Rob Wealth',
    defZh: '劫财与日主同类异性，代表冲劲、争取与合伙，助身有力，但也象征争夺、破财与合作中的摩擦。',
    defEn: 'Rob Wealth shares the element but opposite polarity — drive, contention and partnership; strong support but also rivalry and money-loss risk.',
    relZh: '劫财帮身（身弱得力），但易夺财、忌财星显露；合伙宜防。',
    relEn: 'It strongly aids a weak self yet tends to seize Wealth — caution in partnerships.',
    src: '十神，《渊海子平》',
  },
]

// ——— 十天干日主性格（10）———
export const RIZHU = [
  {
    id: 'jiamu', kind: 'rizhu', zh: '甲木', en: 'Jia Wood',
    defZh: '甲为阳木，象参天大树、栋梁之材。甲木日主多正直上进、有担当、好为人先，认定方向就一路向上、不轻易低头；优点是有骨气、扛得起事，要留意的是太刚易折、不够圆融。',
    defEn: 'Jia is yang Wood — the towering tree. Jia Day Masters tend to be upright, ambitious and responsible, growing steadily toward a goal once set. The strength is backbone; the watch-out is being too rigid to bend.',
    relZh: '甲木旺喜金来修剪（官杀）、火来通明（食伤）；弱则喜水生、木助。',
    relEn: 'A strong Jia welcomes Metal to prune it and Fire to express; a weak Jia wants Water and Wood for support.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'yimu', kind: 'rizhu', zh: '乙木', en: 'Yi Wood',
    defZh: '乙为阴木，象花草藤蔓。乙木日主柔韧、善借势、适应力强，能在夹缝里生长，待人温和有弹性；优点是韧性足、会变通，要留意的是有时缺主见、易随环境。',
    defEn: 'Yi is yin Wood — vines and grasses. Yi Day Masters are supple and adaptive, thriving by leaning and bending, gentle and resilient. The strength is flexibility; the watch-out is leaning too much on circumstances.',
    relZh: '乙木喜水滋、忌金克太过；得火吐秀则灵动有才。',
    relEn: 'Yi likes Water’s nourishment, dislikes excess Metal; with Fire it turns expressive and bright.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'binghuo', kind: 'rizhu', zh: '丙火', en: 'Bing Fire',
    defZh: '丙为阳火，象太阳。丙火日主热情外向、光明磊落、有感染力，来得快去得也快、藏不住话；优点是真诚有热度、能带动人，要留意的是性急、情绪起伏大。',
    defEn: 'Bing is yang Fire — the sun. Bing Day Masters are warm, outgoing and radiant, quick to light up and unable to hide much. The strength is sincere energy that moves others; the watch-out is impatience and mood swings.',
    relZh: '丙火旺喜水既济、土泄秀；弱则喜木生、火助。',
    relEn: 'A strong Bing likes Water to balance it and Earth to release; a weak Bing wants Wood and Fire.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'dinghuo', kind: 'rizhu', zh: '丁火', en: 'Ding Fire',
    defZh: '丁为阴火，象灯烛星火。丁火日主温暖内敛、心思细腻、有奉献精神，照人而不刺眼、重情念旧；优点是体贴有温度，要留意的是想得多、易多愁。',
    defEn: 'Ding is yin Fire — candle and starlight. Ding Day Masters are warm yet reserved, delicate and giving, gentle rather than glaring. The strength is thoughtful warmth; the watch-out is overthinking and melancholy.',
    relZh: '丁火喜木生、喜甲木引丁；忌水过克，水多则光弱。',
    relEn: 'Ding likes Wood to feed it; too much Water dims its light.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'wutu', kind: 'rizhu', zh: '戊土', en: 'Wu Earth',
    defZh: '戊为阳土，象城墙高山、广厚大地。戊土日主稳重可靠、包容厚道、重信用，是别人愿意托付的一类，慢热而有定力；优点是踏实扛事，要留意的是偏固执、转身慢。',
    defEn: 'Wu is yang Earth — city walls and broad land. Wu Day Masters are steady, inclusive and trustworthy, slow to warm but solid. The strength is dependability; the watch-out is stubbornness and slow pivots.',
    relZh: '戊土喜火生、木疏（官杀）、水润（财）调候；过燥过湿皆需调。',
    relEn: 'Wu likes Fire to nourish, Wood to loosen it and Water to moisten — balance of dry and damp matters.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'jitu', kind: 'rizhu', zh: '己土', en: 'Ji Earth',
    defZh: '己为阴土，象田园湿土。己土日主细致务实、能容纳、善积累，内秀而低调，把事一点点做扎实；优点是踏实会过日子，要留意的是有时计较、放不太开。',
    defEn: 'Ji is yin Earth — cultivated field soil. Ji Day Masters are meticulous, practical and accommodating, quietly capable and good at steady accumulation. The strength is grounded diligence; the watch-out is fussing over small things.',
    relZh: '己土喜火暖、水润，忌木克太过；得丙火则万物生发。',
    relEn: 'Ji likes Fire’s warmth and Water’s moisture; with Bing Fire it becomes fertile.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'gengjin', kind: 'rizhu', zh: '庚金', en: 'Geng Metal',
    defZh: '庚为阳金，象刀剑矿石、肃杀之气。庚金日主刚毅果断、讲义气有原则、敢作敢当，对就是对、错就是错；优点是有魄力、靠得住，要留意的是太硬、易伤人也易碰壁。',
    defEn: 'Geng is yang Metal — blade and ore. Geng Day Masters are firm and decisive, loyal and principled, calling things as they are. The strength is resolve; the watch-out is a hardness that cuts both ways.',
    relZh: '庚金喜火炼成器、水淘其锋；强则喜木为财、水泄其秀。',
    relEn: 'Geng likes Fire to forge it and Water to refine its edge; when strong, Wood and Water put it to use.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'xinjin', kind: 'rizhu', zh: '辛金', en: 'Xin Metal',
    defZh: '辛为阴金，象珠玉首饰。辛金日主精致敏感、要求高、重品味与体面，自尊心强、心思细；优点是有格调、做事讲究，要留意的是易挑剔、玻璃心。',
    defEn: 'Xin is yin Metal — jewelry and gems. Xin Day Masters are refined and sensitive, with high standards and a love of taste and dignity. The strength is elegance and care; the watch-out is being easily wounded or overly critical.',
    relZh: '辛金喜水洗其辉、忌火过克；得壬水吐秀则清贵。',
    relEn: 'Xin likes Water to reveal its shine and dislikes excess Fire; with Ren Water it turns elegant.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'renshui', kind: 'rizhu', zh: '壬水', en: 'Ren Water',
    defZh: '壬为阳水，象江河大海。壬水日主聪明大气、思路流动、包容有谋略，喜自由不爱被框；优点是机变有格局，要留意的是易善变、定力需后天磨。',
    defEn: 'Ren is yang Water — rivers and seas. Ren Day Masters are bright and expansive, fluid in thought, strategic and freedom-loving. The strength is resourceful breadth; the watch-out is changeability.',
    relZh: '壬水喜土制成堤（官杀）、木泄其秀（食伤）；忌泛滥无制。',
    relEn: 'Ren likes Earth to bank it and Wood to channel it; unchecked, it floods.',
    src: '子平日主论，《滴天髓》',
  },
  {
    id: 'guishui', kind: 'rizhu', zh: '癸水', en: 'Gui Water',
    defZh: '癸为阴水，象雨露泉流。癸水日主细腻内敛、想象力丰富、有耐心善体察，柔中带韧、滋润万物；优点是敏感有灵气，要留意的是想太多、易钻牛角尖。',
    defEn: 'Gui is yin Water — rain and dew. Gui Day Masters are delicate and inward, imaginative and patient, soft yet enduring. The strength is intuitive sensitivity; the watch-out is over-rumination.',
    relZh: '癸水喜金生、忌土浊；得辛金清源则灵秀。',
    relEn: 'Gui likes Metal to feed it and dislikes muddying Earth; clear Metal makes it bright.',
    src: '子平日主论，《滴天髓》',
  },
]
