export const STRINGS = {
  zh: {
    badge: '传统文化 · 娱乐参考',
    brand: '一命',
    brandSub: 'ONEMING',
    proverb: ['一命', '二运', '三风水', '四积阴德', '五读书'],
    proverbFull: '一命二运三风水，四积阴德五读书',
    heroSeo: '一命二运三风水，免费排盘看懂你的八字命盘。',
    heroLead: '排出你的四柱八字与五行分布，并解释命盘里出现的每一个专业术语。不预测吉凶、不改运。',
    cta: '排我的命盘',
    formTitle: '输入出生信息',
    formHint: '按公历（阳历）填写。出生时间越准，时柱越准；不确定时辰可先选个大概。',
    date: '出生日期',
    time: '出生时间',
    gender: '性别',
    male: '男',
    female: '女',
    submit: '排盘',
    reset: '重新排',
    resultTitle: '你的命盘',
    chartLabel: '四柱八字',
    elementsLabel: '五行分布',
    toneTitle: '性格基调',
    balanceTitle: '五行参考',
    readingTitle: '命盘解读',
    strengthLabel: '旺衰',
    favorLabel: '喜用',
    glossaryHint: '点带下划线的词可看解释',
    termRelation: '它和别的怎么互动',
    termSource: '出处',
    termClose: '关闭',
    readingFoot: '以上为对你天生倾向的参考性描述，基于传统命理（扶抑法），仅供文化与自我参考，非命定。',
    shareLabel: '保存 / 分享命盘',
    shareDone: '链接已复制 ✓',
    shareHint: '复制专属链接，可收藏或发给朋友',
    cardLabel: '生成命盘卡片',
    cardVibe: '氛围卡',
    cardFull: '完整卡',
    cardDownload: '保存图片',
    cardClose: '关闭',
    cardPrivacy: '完整卡会显示你的四柱八字（含时辰）。介意隐私就用氛围卡。',
    cardSaved: '已生成，长按或点保存到相册',
    cardTagline: '免费排八字 · 传统文化娱乐参考',
    cardDayMaster: '日主',
    cardFavor: '喜用',
    cardElements: '五行',
    relatedTitle: '相关阅读',
    termsBarPrefix: '本命盘涉及',
    termsBarSuffix: '个术语，点击查看解释：',
    trustTitle: '以古籍为据',
    trustBody: '解读框架源出《渊海子平》《滴天髓》《三命通会》等公有经典，词条皆标注出处。计算是确定性的规则，AI 只负责措辞——只谈性格倾向，不预测、不改运。',
    trustLink: '了解我们如何使用 AI',
    footTerms: '用户协议',
    footPrivacy: '隐私说明',
    footAi: 'AI 生成说明',
    dayMaster: '日主',
    shengxiao: '生肖',
    xingzuo: '星座',
    nayin: '纳音',
    tipEyebrow: '支持一命',
    tipTitle: '请我喝杯茶',
    tipBody: '一命永远免费，也不收算命的钱。如果它帮你消磨了点时间、或你单纯想让这个小站继续开着，可以请我喝杯茶——纯自愿，不解锁任何内容。',
    tipCta: '请喝杯茶',
    shopEyebrow: '一命周边',
    shopTitle: '周边筹备中',
    shopBody: '按五行做的一套手串与文玩选物正在筹备，上线后会放在这里。当作喜欢的物件来戴就好。',
    shopSoon: '敬请期待',
    disclaimerTitle: '说在前面',
    disclaimer: '本站内容基于传统命理（八字/五行）排盘，仅供文化欣赏与娱乐参考，不构成任何关于健康、婚姻、财运、投资或人生决策的建议或保证。重要决定请相信自己、咨询专业人士。八字计算在你的浏览器本地完成，我们不收集你的出生信息。',
    langBtn: 'EN',
    footerTag: '一命二运三风水，四积阴德五读书',
  },
  en: {
    badge: 'Tradition · For fun',
    brand: 'ONE\nMING',
    brandSub: '一命',
    proverb: ['Fate', 'Luck', 'Feng shui', 'Good deeds', 'Learning'],
    proverbFull: 'First fate, then luck, then feng shui — then good deeds, then learning.',
    heroSeo: 'A free BaZi chart — with every term in it explained.',
    heroLead: 'Your Four Pillars and Five Elements, plus plain-language explanations of every technical term in your chart. No predictions, no fate-changing.',
    cta: 'Draw my chart',
    formTitle: 'Your birth details',
    formHint: 'Use the Gregorian (solar) calendar. A precise birth time gives a precise Hour pillar; pick the closest if unsure.',
    date: 'Date of birth',
    time: 'Time of birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    submit: 'Read chart',
    reset: 'Start over',
    resultTitle: 'Your chart',
    chartLabel: 'Four Pillars · BaZi',
    elementsLabel: 'Five Elements',
    toneTitle: 'Your tone',
    balanceTitle: 'Elements at a glance',
    readingTitle: 'Your reading',
    strengthLabel: 'Strength',
    favorLabel: 'Favors',
    glossaryHint: 'Tap an underlined term for its meaning',
    termRelation: 'How it interacts',
    termSource: 'Source',
    termClose: 'Close',
    readingFoot: 'A reflective description of natural tendencies, based on traditional BaZi (strength & favorable-element method). For culture and self-reflection only — not a fixed fate.',
    shareLabel: 'Save / Share',
    shareDone: 'Link copied ✓',
    shareHint: 'Copy your personal link to keep or send to a friend',
    cardLabel: 'Create card',
    cardVibe: 'Vibe card',
    cardFull: 'Full card',
    cardDownload: 'Save image',
    cardClose: 'Close',
    cardPrivacy: 'The full card shows your Four Pillars (incl. birth hour). Use the vibe card if you prefer privacy.',
    cardSaved: 'Ready — long-press or tap to save',
    cardTagline: 'Free BaZi · tradition, for fun',
    cardDayMaster: 'Day Master',
    cardFavor: 'Favors',
    cardElements: 'Five Elements',
    relatedTitle: 'Related reading',
    termsBarPrefix: 'This chart involves',
    termsBarSuffix: 'terms — tap to see what they mean:',
    trustTitle: 'Grounded in the classics',
    trustBody: 'The reading framework comes from public-domain classics such as Yuanhai Ziping, Ditian Sui and Sanming Tonghui, with sources cited on every glossary entry. The math is deterministic; AI only handles the wording — personality tendencies only, no prediction, no fate-changing.',
    trustLink: 'How we use AI',
    footTerms: 'Terms',
    footPrivacy: 'Privacy',
    footAi: 'AI Notice',
    dayMaster: 'Day Master',
    shengxiao: 'Zodiac',
    xingzuo: 'Sun sign',
    nayin: 'Na Yin',
    tipEyebrow: 'Support ONEMING',
    tipTitle: 'Buy me a tea',
    tipBody: 'ONEMING is free, and the reading never costs anything. If it passed some time for you, or you just want to keep this little site running, you can buy me a tea — entirely optional, and it unlocks nothing.',
    tipCta: 'Buy a tea',
    shopEyebrow: 'ONEMING goods',
    shopTitle: 'Shop in the works',
    shopBody: 'A small set of element-themed beads and curios is on the way, and will live here once it launches. Wear them simply as objects you like.',
    shopSoon: 'Coming soon',
    disclaimerTitle: 'Before you start',
    disclaimer: 'This site draws traditional Chinese charts (BaZi / Five Elements) for cultural interest and entertainment only. Nothing here is advice about, or a guarantee of, health, relationships, money, investing or any life decision. For real choices, trust yourself and talk to a professional. Charts are computed locally in your browser; we do not collect your birth data.',
    langBtn: '中文',
    footerTag: 'First fate, second luck, third feng shui.',
  },
}
