export const STRINGS = {
  zh: {
    badge: '传统文化 · 娱乐参考',
    brand: '一命',
    brandSub: 'ONEMING',
    proverb: ['一命', '二运', '三风水', '四积阴德', '五读书'],
    proverbFull: '一命二运三风水，四积阴德五读书',
    heroLead: '命排在第一位。先把你的那一组八个字排出来，看看天生这副牌长什么样。',
    cta: '排我的命盘',
    formTitle: '输入出生信息',
    formHint: '按公历（阳历）填写。出生时间越准，时柱越准；不确定时辰可先选个大概。',
    date: '出生日期',
    time: '出生时间',
    gender: '性别',
    male: '男',
    female: '女',
    submit: '排盘',
    reset: '重新排',
    resultTitle: '你的命盘',
    chartLabel: '四柱八字',
    elementsLabel: '五行分布',
    toneTitle: '性格基调',
    balanceTitle: '五行参考',
    dayMaster: '日主',
    shengxiao: '生肖',
    xingzuo: '星座',
    nayin: '纳音',
    shopEyebrow: '一命周边',
    shopTitle: '把这副牌，戴在手上',
    shopBody: '我们按五行做了一套手串与文玩选物——当作喜欢的物件来戴就好，是寄托不是承诺。算命永远免费，店在另一边。',
    shopCta: '逛逛选物',
    disclaimerTitle: '说在前面',
    disclaimer: '本站内容基于传统命理（八字/五行）排盘，仅供文化欣赏与娱乐参考，不构成任何关于健康、婚姻、财运、投资或人生决策的建议或保证。重要决定请相信自己、咨询专业人士。八字计算在你的浏览器本地完成，我们不收集你的出生信息。',
    langBtn: 'EN',
    footerTag: '一命二运三风水，四积阴德五读书',
  },
  en: {
    badge: 'Tradition · For fun',
    brand: 'ONE\nMING',
    brandSub: '一命',
    proverb: ['Fate', 'Luck', 'Feng shui', 'Good deeds', 'Learning'],
    proverbFull: 'First fate, then luck, then feng shui — then good deeds, then learning.',
    heroLead: 'In the old saying, fate comes first. Start by drawing your eight characters — the hand you were dealt at birth.',
    cta: 'Draw my chart',
    formTitle: 'Your birth details',
    formHint: 'Use the Gregorian (solar) calendar. A precise birth time gives a precise Hour pillar; pick the closest if unsure.',
    date: 'Date of birth',
    time: 'Time of birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    submit: 'Read chart',
    reset: 'Start over',
    resultTitle: 'Your chart',
    chartLabel: 'Four Pillars · BaZi',
    elementsLabel: 'Five Elements',
    toneTitle: 'Your tone',
    balanceTitle: 'Elements at a glance',
    dayMaster: 'Day Master',
    shengxiao: 'Zodiac',
    xingzuo: 'Sun sign',
    nayin: 'Na Yin',
    shopEyebrow: 'ONEMING goods',
    shopTitle: 'Wear the hand you were dealt',
    shopBody: 'A small set of element-themed beads and curios. Wear them as objects you like — a keepsake, not a promise. The reading is always free; the shop lives over here.',
    shopCta: 'Browse the shop',
    disclaimerTitle: 'Before you start',
    disclaimer: 'This site draws traditional Chinese charts (BaZi / Five Elements) for cultural interest and entertainment only. Nothing here is advice about, or a guarantee of, health, relationships, money, investing or any life decision. For real choices, trust yourself and talk to a professional. Charts are computed locally in your browser; we do not collect your birth data.',
    langBtn: '中文',
    footerTag: 'First fate, second luck, third feng shui.',
  },
}
