// 一命 · 命理知识库词条（第一批）
// 口径：取公有概念，自己的话重写；标注公有古籍出处；只解释、不预测、不改运。
// 每条：id / 术语(中英) / 是什么 / 关系(它和别的怎么互动) / 出处

export const TERMS = [
  {
    id: 'bazi', zh: '八字', en: 'BaZi (Eight Characters)',
    defZh: '出生的年、月、日、时四组干支，共八个字，是命理推算的基础盘面。',
    defEn: 'The eight characters formed by the Heavenly Stem and Earthly Branch of your birth year, month, day and hour — the base chart of the reading.',
    relZh: '八字又称"四柱"，每一柱由一个天干和一个地支组成。',
    relEn: 'Also called the "Four Pillars"; each pillar is one Stem over one Branch.',
    src: '体系定型见《渊海子平》（宋）',
  },
  {
    id: 'sizhu', zh: '四柱', en: 'Four Pillars',
    defZh: '年柱、月柱、日柱、时柱。分别大致对应祖辈与早年、父母与青年、自身与成年、子女与晚年。',
    defEn: 'Year, Month, Day and Hour pillars — loosely mapping to early life, youth, the self/adulthood, and later years.',
    relZh: '日柱的天干（日主）是整张盘的核心，其余三柱都围绕它来读。',
    relEn: 'The Day stem (Day Master) is the chart’s center; the other pillars are read in relation to it.',
    src: '《渊海子平》《三命通会》（明）',
  },
  {
    id: 'rizhu', zh: '日主（日元）', en: 'Day Master',
    defZh: '出生那天的天干，代表"你自己"。整张命盘以它为基准来判断强弱与喜忌。',
    defEn: 'The Heavenly Stem of your birth day — it represents "you". The whole chart is judged relative to it.',
    relZh: '日主的五行决定了哪些字在帮它（印、比劫）、哪些在消耗它（食伤、财、官杀）。',
    relEn: 'The Day Master’s element decides which characters support it (Resource, Companion) and which drain it (Output, Wealth, Authority).',
    src: '《滴天髓》',
  },
  {
    id: 'wuxing', zh: '五行', en: 'Five Elements',
    defZh: '木、火、土、金、水五种基本能量。彼此有"生"（木生火…）与"克"（木克土…）的循环关系。',
    defEn: 'Wood, Fire, Earth, Metal, Water — five basic energies linked by cycles of generation (Wood feeds Fire…) and control (Wood parts Earth…).',
    relZh: '一张盘里五行的多寡与生克，决定了它偏旺还是偏弱、喜什么忌什么。',
    relEn: 'The balance and interaction of the five elements in a chart drive its strength and what it favors.',
    src: '源自《尚书·洪范》，命理化用见子平诸书',
  },
  {
    id: 'tiangan', zh: '天干', en: 'Heavenly Stems',
    defZh: '甲乙丙丁戊己庚辛壬癸十个符号，各配一种五行与阴阳，是干支的"上半"。',
    defEn: 'The ten stems (Jiǎ, Yǐ, Bǐng…), each carrying an element and a yin/yang polarity — the upper half of a pillar.',
    relZh: '日主就是日柱的天干；天干透出什么，往往代表更显性、外在的特质。',
    relEn: 'The Day Master is a stem; what shows in the stems tends to read as more outward, visible traits.',
    src: '《三命通会》',
  },
  {
    id: 'dizhi', zh: '地支', en: 'Earthly Branches',
    defZh: '子丑寅卯辰巳午未申酉戌亥十二个符号，对应生肖与月令，是干支的"下半"。',
    defEn: 'The twelve branches (Zǐ, Chǒu, Yín…), tied to the zodiac and the months — the lower half of a pillar.',
    relZh: '月支（月令）力量最重，是判断日主旺衰的首要依据。',
    relEn: 'The Month branch carries the most weight and is the primary basis for judging the Day Master’s strength.',
    src: '《三命通会》',
  },
  {
    id: 'deling', zh: '得令 / 失令', en: 'In-season / Out-of-season',
    defZh: '看月支的五行是否在帮日主：同它或生它为"得令"（当季得力），否则为"失令"。',
    defEn: 'Whether the Month branch supports the Day Master: same or generating element = in-season (supported); otherwise out-of-season.',
    relZh: '得令是判旺衰里权重最高的一项——月令当季，日主先有了底气。',
    relEn: 'Being in-season is the single heaviest factor in judging strength.',
    src: '《滴天髓》旺衰论',
  },
  {
    id: 'shenqiang', zh: '身强（偏旺）', en: 'Strong Day Master',
    defZh: '日主得到的帮扶（得令 + 印、比劫多）较多，能量偏旺。',
    defEn: 'The Day Master gets ample support (in-season plus many Resource/Companion characters); its energy runs strong.',
    relZh: '身强者喜"疏泄"——用食伤、财、官杀把多余旺气导出去，更显从容。',
    relEn: 'A strong Day Master favors release — Output, Wealth and Authority channel the surplus.',
    src: '扶抑法，《渊海子平》《滴天髓》',
  },
  {
    id: 'shenruo', zh: '身弱（偏弱）', en: 'Weak Day Master',
    defZh: '日主得到的帮扶较少（失令或印、比劫少），能量偏弱。',
    defEn: 'The Day Master gets little support (out-of-season or few Resource/Companion characters); its energy runs weaker.',
    relZh: '身弱者喜"生扶"——用印、比劫来帮身，性格上也更擅长借力与协作。',
    relEn: 'A weak Day Master favors support — Resource and Companion reinforce it; the temperament leans collaborative.',
    src: '扶抑法，《渊海子平》《滴天髓》',
  },
  {
    id: 'zhonghe', zh: '中和', en: 'Balanced',
    defZh: '日主的帮扶与消耗大致相当，不偏旺也不偏弱。',
    defEn: 'Support and drain on the Day Master are roughly even — neither strong nor weak.',
    relZh: '中和之命可塑性强、能屈能伸，喜用上多为"缺什么补什么"。',
    relEn: 'A balanced chart is adaptable; what it favors is usually whatever element is least present.',
    src: '《滴天髓》',
  },
  {
    id: 'xiyong', zh: '喜用神', en: 'Favorable Element',
    defZh: '让整张盘更平衡的五行方向：弱则扶（喜印、比劫），强则抑（喜食伤、财、官杀）。',
    defEn: 'The element direction that brings the chart toward balance: support if weak, drain if strong.',
    relZh: '喜用对应的是"性格上顺手、可有意识培养的方向"，不是"戴什么改运"。',
    relEn: 'It points to natural, cultivable directions in temperament — not a charm to "change fate".',
    src: '用神扶抑法，《滴天髓》',
  },
  {
    id: 'bijie', zh: '比劫（比肩 / 劫财）', en: 'Companion (Friend / Rival)',
    defZh: '与日主同五行的字，像"同类、同伴、竞争者"，帮身的力量。',
    defEn: 'Characters of the same element as the Day Master — peers, allies, rivals; they reinforce the self.',
    relZh: '身弱时比劫是助力；身旺时比劫过多反而要靠食伤、财来疏导。',
    relEn: 'Helpful when the Day Master is weak; too many when it is already strong needs channeling.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'yinshou', zh: '印（正印 / 偏印）', en: 'Resource',
    defZh: '生日主的五行，像"母亲、靠山、学习与滋养"的力量。',
    defEn: 'The element that generates the Day Master — nurture, backing, learning and support.',
    relZh: '印生身，是身弱者的重要帮手；与官杀相邻时，常有"以学化压力"的味道。',
    relEn: 'Resource feeds the self — key support when weak; next to Authority it often reads as turning pressure into learning.',
    src: '十神，《三命通会》',
  },
  {
    id: 'shishang', zh: '食伤（食神 / 伤官）', en: 'Output',
    defZh: '日主所生的五行，像"表达、才华、创造与输出"。',
    defEn: 'The element the Day Master generates — expression, talent, creativity and output.',
    relZh: '食伤泄身，是身旺者的好出口；它也"克"官杀，常表现为不爱被管。',
    relEn: 'Output releases a strong self; it also counters Authority, often reading as a dislike of being controlled.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'caixing', zh: '财（正财 / 偏财）', en: 'Wealth',
    defZh: '日主所克的五行，像"财物、资源、目标与掌控对象"。',
    defEn: 'The element the Day Master controls — assets, resources, the things one manages or pursues.',
    relZh: '财耗身，需要日主有力才"担得起财"；身弱见重财，反而力不从心。',
    relEn: 'Wealth draws on the self — a strong Day Master can "carry" it; a weak one finds heavy Wealth taxing.',
    src: '十神，《三命通会》',
  },
  {
    id: 'guansha', zh: '官杀（正官 / 七杀）', en: 'Authority',
    defZh: '克日主的五行，像"规则、责任、压力、权威与约束"。',
    defEn: 'The element that controls the Day Master — rules, responsibility, pressure, authority and constraint.',
    relZh: '官杀克身：身强者视为历练与舞台，身弱者则需印来化、比劫来扛。',
    relEn: 'Authority restrains the self: a stage for the strong, something the weak resolve via Resource or Companion.',
    src: '十神，《渊海子平》',
  },
  {
    id: 'nayin', zh: '纳音', en: 'Na Yin',
    defZh: '把每柱干支再归到一种"音律五行"，给出如"山头火""城头土"这类形象化的别称。',
    defEn: 'A secondary five-element mapping of each pillar, giving evocative names like "Mountain Fire" or "City Wall Earth".',
    relZh: '纳音是一层补充的象征性描述，现代多作意象参考，不作主要判断依据。',
    relEn: 'A supplementary symbolic layer — today used mainly as imagery, not a primary basis for judgment.',
    src: '《三命通会·纳音》',
  },
  {
    id: 'shengxiao', zh: '生肖', en: 'Zodiac',
    defZh: '由出生年的地支对应的十二种动物（鼠牛虎兔…）。',
    defEn: 'The twelve animals (Rat, Ox, Tiger, Rabbit…) tied to the Earthly Branch of your birth year.',
    relZh: '生肖只取年支一项，是八字里很小的一部分，不等于整张命盘。',
    relEn: 'The zodiac uses only the year branch — a small slice of the full chart, not the whole reading.',
    src: '民俗与命理通用',
  },
]

export const TERM_BY_ID = Object.fromEntries(TERMS.map((t) => [t.id, t]))
